-- 상품 별 오프라인 매출 구하기
SELECT PRODUCT_CODE, (SUM(P.Price * O.SALES_AMOUNT)) as SALES
FROM PRODUCT as P INNER JOIN OFFLINE_SALE as O 
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES desc, P.PRODUCT_CODE asc